"""
NexScan - Service Database
Comprehensive port-to-service mapping with CPE identifiers.
"""

SERVICES = {
    # TCP services
    ("tcp", 1): {"name": "tcpmux", "description": "TCP Port Service Multiplexer"},
    ("tcp", 7): {"name": "echo", "description": "Echo"},
    ("tcp", 9): {"name": "discard", "description": "Discard"},
    ("tcp", 11): {"name": "systat", "description": "Active Users"},
    ("tcp", 13): {"name": "daytime", "description": "Daytime"},
    ("tcp", 17): {"name": "qotd", "description": "Quote of the Day"},
    ("tcp", 19): {"name": "chargen", "description": "Character Generator"},
    ("tcp", 20): {"name": "ftp-data", "description": "FTP Data Transfer"},
    ("tcp", 21): {"name": "ftp", "description": "File Transfer Protocol", "cpe": "cpe:/a:ftp"},
    ("tcp", 22): {"name": "ssh", "description": "Secure Shell", "cpe": "cpe:/a:openssh"},
    ("tcp", 23): {"name": "telnet", "description": "Telnet"},
    ("tcp", 25): {"name": "smtp", "description": "Simple Mail Transfer Protocol"},
    ("tcp", 37): {"name": "time", "description": "Time"},
    ("tcp", 43): {"name": "whois", "description": "WHOIS"},
    ("tcp", 53): {"name": "dns", "description": "Domain Name System"},
    ("tcp", 67): {"name": "dhcp", "description": "DHCP Server"},
    ("tcp", 68): {"name": "dhcp-client", "description": "DHCP Client"},
    ("tcp", 69): {"name": "tftp", "description": "Trivial File Transfer Protocol"},
    ("tcp", 70): {"name": "gopher", "description": "Gopher"},
    ("tcp", 79): {"name": "finger", "description": "Finger"},
    ("tcp", 80): {"name": "http", "description": "Hypertext Transfer Protocol", "cpe": "cpe:/a:apache:http_server"},
    ("tcp", 88): {"name": "kerberos", "description": "Kerberos Authentication"},
    ("tcp", 102): {"name": "iso-tsap", "description": "ISO-TSAP"},
    ("tcp", 110): {"name": "pop3", "description": "Post Office Protocol v3"},
    ("tcp", 111): {"name": "rpcbind", "description": "Remote Procedure Call Bind"},
    ("tcp", 113): {"name": "ident", "description": "Identification Protocol"},
    ("tcp", 119): {"name": "nntp", "description": "Network News Transfer Protocol"},
    ("tcp", 123): {"name": "ntp", "description": "Network Time Protocol"},
    ("tcp", 135): {"name": "msrpc", "description": "Microsoft RPC"},
    ("tcp", 137): {"name": "netbios-ns", "description": "NetBIOS Name Service"},
    ("tcp", 138): {"name": "netbios-dgm", "description": "NetBIOS Datagram Service"},
    ("tcp", 139): {"name": "netbios-ssn", "description": "NetBIOS Session Service"},
    ("tcp", 143): {"name": "imap", "description": "Internet Message Access Protocol"},
    ("tcp", 161): {"name": "snmp", "description": "Simple Network Management Protocol"},
    ("tcp", 162): {"name": "snmptrap", "description": "SNMP Trap"},
    ("tcp", 179): {"name": "bgp", "description": "Border Gateway Protocol"},
    ("tcp", 194): {"name": "irc", "description": "Internet Relay Chat"},
    ("tcp", 220): {"name": "imap3", "description": "IMAP v3"},
    ("tcp", 264): {"name": "bgmp", "description": "Border Gateway Multicast Protocol"},
    ("tcp", 318): {"name": "tsp", "description": "Time Stamp Protocol"},
    ("tcp", 389): {"name": "ldap", "description": "Lightweight Directory Access Protocol"},
    ("tcp", 443): {"name": "https", "description": "HTTP Secure", "cpe": "cpe:/a:apache:http_server"},
    ("tcp", 444): {"name": "snpp", "description": "Simple Network Paging Protocol"},
    ("tcp", 445): {"name": "microsoft-ds", "description": "Microsoft Directory Services / SMB"},
    ("tcp", 464): {"name": "kpasswd", "description": "Kerberos Password Change"},
    ("tcp", 465): {"name": "smtps", "description": "SMTP over SSL"},
    ("tcp", 500): {"name": "isakmp", "description": "Internet Security Association / IKE"},
    ("tcp", 512): {"name": "exec", "description": "Remote Process Execution"},
    ("tcp", 513): {"name": "login", "description": "Remote Login"},
    ("tcp", 514): {"name": "shell", "description": "Remote Shell / Syslog"},
    ("tcp", 515): {"name": "printer", "description": "Line Printer Daemon"},
    ("tcp", 520): {"name": "rip", "description": "Routing Information Protocol"},
    ("tcp", 523): {"name": "ibm-db2", "description": "IBM DB2"},
    ("tcp", 530): {"name": "courier", "description": "Courier"},
    ("tcp", 548): {"name": "afp", "description": "Apple Filing Protocol"},
    ("tcp", 554): {"name": "rtsp", "description": "Real Time Streaming Protocol"},
    ("tcp", 587): {"name": "submission", "description": "Email Submission"},
    ("tcp", 593): {"name": "http-rpc-epmap", "description": "HTTP RPC Endpoint Mapper"},
    ("tcp", 631): {"name": "ipp", "description": "Internet Printing Protocol"},
    ("tcp", 636): {"name": "ldaps", "description": "LDAP over SSL"},
    ("tcp", 646): {"name": "ldp", "description": "Label Distribution Protocol"},
    ("tcp", 691): {"name": "resvc", "description": "MS Exchange Routing"},
    ("tcp", 860): {"name": "iscsi", "description": "iSCSI"},
    ("tcp", 873): {"name": "rsync", "description": "Rsync"},
    ("tcp", 902): {"name": "vmware", "description": "VMware Server"},
    ("tcp", 989): {"name": "ftps-data", "description": "FTP over SSL (data)"},
    ("tcp", 990): {"name": "ftps", "description": "FTP over SSL (control)"},
    ("tcp", 993): {"name": "imaps", "description": "IMAP over SSL"},
    ("tcp", 995): {"name": "pop3s", "description": "POP3 over SSL"},
    ("tcp", 1025): {"name": "nfs-or-iis", "description": "Network File System / IIS"},
    ("tcp", 1026): {"name": "msrpc", "description": "Microsoft RPC"},
    ("tcp", 1027): {"name": "msrpc", "description": "Microsoft RPC"},
    ("tcp", 1080): {"name": "socks", "description": "SOCKS Proxy"},
    ("tcp", 1194): {"name": "openvpn", "description": "OpenVPN"},
    ("tcp", 1214): {"name": "fasttrack", "description": "FastTrack P2P"},
    ("tcp", 1241): {"name": "nessus", "description": "Nessus Security Scanner"},
    ("tcp", 1311): {"name": "rxmon", "description": "Dell OpenManage"},
    ("tcp", 1337): {"name": "waste", "description": "WASTE Encrypted P2P"},
    ("tcp", 1433): {"name": "mssql", "description": "Microsoft SQL Server", "cpe": "cpe:/a:microsoft:sql_server"},
    ("tcp", 1434): {"name": "mssql-monitor", "description": "MS SQL Monitor"},
    ("tcp", 1521): {"name": "oracle", "description": "Oracle Database", "cpe": "cpe:/a:oracle:database_server"},
    ("tcp", 1604): {"name": "citrix-ica", "description": "Citrix ICA"},
    ("tcp", 1645): {"name": "radius", "description": "RADIUS Authentication"},
    ("tcp", 1723): {"name": "pptp", "description": "Point-to-Point Tunneling Protocol"},
    ("tcp", 1755): {"name": "ms-streaming", "description": "Microsoft Media Server"},
    ("tcp", 1812): {"name": "radius-auth", "description": "RADIUS Authentication"},
    ("tcp", 1813): {"name": "radius-acct", "description": "RADIUS Accounting"},
    ("tcp", 1883): {"name": "mqtt", "description": "MQTT (IoT Messaging)"},
    ("tcp", 1900): {"name": "upnp", "description": "Universal Plug and Play"},
    ("tcp", 2049): {"name": "nfs", "description": "Network File System"},
    ("tcp", 2082): {"name": "cpanel", "description": "cPanel HTTP"},
    ("tcp", 2083): {"name": "cpanel-ssl", "description": "cPanel HTTPS"},
    ("tcp", 2100): {"name": "amiganetfs", "description": "Amiga Network File System"},
    ("tcp", 2121): {"name": "ftp-alt", "description": "FTP Alternate"},
    ("tcp", 2181): {"name": "zookeeper", "description": "Apache ZooKeeper"},
    ("tcp", 2222): {"name": "ssh-alt", "description": "SSH Alternate"},
    ("tcp", 2375): {"name": "docker", "description": "Docker API (insecure)"},
    ("tcp", 2376): {"name": "docker-ssl", "description": "Docker API (SSL)"},
    ("tcp", 2379): {"name": "etcd-client", "description": "etcd Client"},
    ("tcp", 2380): {"name": "etcd-peer", "description": "etcd Peer"},
    ("tcp", 2483): {"name": "oracle-tns", "description": "Oracle TNS Listener"},
    ("tcp", 2484): {"name": "oracle-tns-ssl", "description": "Oracle TNS SSL"},
    ("tcp", 3000): {"name": "http-alt", "description": "HTTP Alternate (Grafana/Node)"},
    ("tcp", 3001): {"name": "http-alt2", "description": "HTTP Alternate"},
    ("tcp", 3128): {"name": "squid-proxy", "description": "Squid HTTP Proxy"},
    ("tcp", 3268): {"name": "msft-gc", "description": "Microsoft Global Catalog"},
    ("tcp", 3269): {"name": "msft-gc-ssl", "description": "Microsoft Global Catalog SSL"},
    ("tcp", 3306): {"name": "mysql", "description": "MySQL Database", "cpe": "cpe:/a:mysql:mysql"},
    ("tcp", 3389): {"name": "rdp", "description": "Remote Desktop Protocol"},
    ("tcp", 3690): {"name": "svn", "description": "Subversion"},
    ("tcp", 4000): {"name": "remoteanything", "description": "Remote Anything"},
    ("tcp", 4369): {"name": "epmd", "description": "Erlang Port Mapper Daemon"},
    ("tcp", 4443): {"name": "https-alt", "description": "HTTPS Alternate"},
    ("tcp", 4444): {"name": "krb524", "description": "Kerberos 524 / Metasploit"},
    ("tcp", 4505): {"name": "saltstack", "description": "SaltStack Publish"},
    ("tcp", 4506): {"name": "saltstack-ret", "description": "SaltStack Return"},
    ("tcp", 4567): {"name": "tram", "description": "TRAM"},
    ("tcp", 4848): {"name": "glassfish", "description": "GlassFish Admin"},
    ("tcp", 5000): {"name": "upnp-http", "description": "UPnP / Flask / Docker Registry"},
    ("tcp", 5001): {"name": "commplex-link", "description": "commplex-link"},
    ("tcp", 5005): {"name": "avt-profile-1", "description": "Java Debug"},
    ("tcp", 5060): {"name": "sip", "description": "Session Initiation Protocol"},
    ("tcp", 5061): {"name": "sips", "description": "SIP over TLS"},
    ("tcp", 5432): {"name": "postgresql", "description": "PostgreSQL", "cpe": "cpe:/a:postgresql:postgresql"},
    ("tcp", 5555): {"name": "adb", "description": "Android Debug Bridge"},
    ("tcp", 5601): {"name": "kibana", "description": "Kibana"},
    ("tcp", 5672): {"name": "amqp", "description": "Advanced Message Queuing Protocol"},
    ("tcp", 5900): {"name": "vnc", "description": "Virtual Network Computing"},
    ("tcp", 5985): {"name": "winrm", "description": "Windows Remote Management HTTP"},
    ("tcp", 5986): {"name": "winrm-ssl", "description": "Windows Remote Management HTTPS"},
    ("tcp", 6000): {"name": "x11", "description": "X Window System"},
    ("tcp", 6379): {"name": "redis", "description": "Redis", "cpe": "cpe:/a:pivotal_software:redis"},
    ("tcp", 6443): {"name": "kubernetes", "description": "Kubernetes API Server"},
    ("tcp", 6667): {"name": "irc", "description": "Internet Relay Chat"},
    ("tcp", 6881): {"name": "bittorrent", "description": "BitTorrent"},
    ("tcp", 7000): {"name": "cassandra", "description": "Apache Cassandra Internode"},
    ("tcp", 7070): {"name": "realserver", "description": "RealAudio / WebSocket"},
    ("tcp", 7443): {"name": "oracleas-https", "description": "Oracle Application Server HTTPS"},
    ("tcp", 7474): {"name": "neo4j", "description": "Neo4j Graph Database"},
    ("tcp", 7547): {"name": "cwmp", "description": "CPE WAN Management Protocol (TR-069)"},
    ("tcp", 8000): {"name": "http-alt", "description": "HTTP Alternate"},
    ("tcp", 8008): {"name": "http-alt", "description": "HTTP Alternate"},
    ("tcp", 8009): {"name": "ajp13", "description": "Apache JServ Protocol"},
    ("tcp", 8080): {"name": "http-proxy", "description": "HTTP Proxy / Tomcat"},
    ("tcp", 8081): {"name": "http-alt", "description": "HTTP Alternate"},
    ("tcp", 8083): {"name": "us-srv", "description": "Unified Messaging"},
    ("tcp", 8086): {"name": "influxdb", "description": "InfluxDB HTTP API"},
    ("tcp", 8088): {"name": "radan-http", "description": "HTTP Alternate"},
    ("tcp", 8089): {"name": "http-alt", "description": "HTTP Alternate"},
    ("tcp", 8161): {"name": "activemq", "description": "ActiveMQ Admin Web Console"},
    ("tcp", 8443): {"name": "https-alt", "description": "HTTPS Alternate"},
    ("tcp", 8444): {"name": "https-alt2", "description": "HTTPS Alternate"},
    ("tcp", 8500): {"name": "consul", "description": "HashiCorp Consul HTTP"},
    ("tcp", 8888): {"name": "jupyter", "description": "Jupyter Notebook"},
    ("tcp", 9000): {"name": "cslistener", "description": "PHP-FPM / SonarQube"},
    ("tcp", 9001): {"name": "tor-orport", "description": "Tor OR Port / Supervisor"},
    ("tcp", 9042): {"name": "cassandra-cql", "description": "Cassandra CQL"},
    ("tcp", 9090): {"name": "prometheus", "description": "Prometheus / Openfire"},
    ("tcp", 9092): {"name": "kafka", "description": "Apache Kafka"},
    ("tcp", 9200): {"name": "elasticsearch", "description": "Elasticsearch HTTP"},
    ("tcp", 9300): {"name": "elasticsearch-node", "description": "Elasticsearch Transport"},
    ("tcp", 9418): {"name": "git", "description": "Git Protocol"},
    ("tcp", 10000): {"name": "webmin", "description": "Webmin"},
    ("tcp", 10250): {"name": "kubernetes-kubelet", "description": "Kubernetes Kubelet API"},
    ("tcp", 11211): {"name": "memcached", "description": "Memcached"},
    ("tcp", 15672): {"name": "rabbitmq-http", "description": "RabbitMQ Management HTTP"},
    ("tcp", 16010): {"name": "hbase", "description": "Apache HBase Master"},
    ("tcp", 20000): {"name": "dnp", "description": "DNP / Usermin"},
    ("tcp", 27017): {"name": "mongodb", "description": "MongoDB", "cpe": "cpe:/a:mongodb:mongodb"},
    ("tcp", 27018): {"name": "mongodb-shard", "description": "MongoDB Shard"},
    ("tcp", 27019): {"name": "mongodb-config", "description": "MongoDB Config"},
    ("tcp", 28017): {"name": "mongodb-http", "description": "MongoDB HTTP Interface"},
    ("tcp", 50070): {"name": "hdfs-namenode", "description": "Hadoop HDFS NameNode"},
    ("tcp", 50090): {"name": "hdfs-secondarynn", "description": "Hadoop Secondary NameNode"},
    ("tcp", 61616): {"name": "activemq", "description": "Apache ActiveMQ"},
    # UDP services
    ("udp", 53): {"name": "dns", "description": "Domain Name System"},
    ("udp", 67): {"name": "dhcp", "description": "DHCP Server"},
    ("udp", 68): {"name": "dhcp-client", "description": "DHCP Client"},
    ("udp", 69): {"name": "tftp", "description": "Trivial File Transfer Protocol"},
    ("udp", 123): {"name": "ntp", "description": "Network Time Protocol"},
    ("udp", 137): {"name": "netbios-ns", "description": "NetBIOS Name Service"},
    ("udp", 138): {"name": "netbios-dgm", "description": "NetBIOS Datagram Service"},
    ("udp", 161): {"name": "snmp", "description": "Simple Network Management Protocol"},
    ("udp", 162): {"name": "snmptrap", "description": "SNMP Trap"},
    ("udp", 500): {"name": "isakmp", "description": "IKE / IPSec"},
    ("udp", 514): {"name": "syslog", "description": "Syslog"},
    ("udp", 520): {"name": "rip", "description": "Routing Information Protocol"},
    ("udp", 1194): {"name": "openvpn", "description": "OpenVPN"},
    ("udp", 1900): {"name": "ssdp", "description": "Simple Service Discovery Protocol"},
    ("udp", 4500): {"name": "ipsec-nat-t", "description": "IPSec NAT Traversal"},
    ("udp", 5353): {"name": "mdns", "description": "Multicast DNS"},
    ("udp", 5355): {"name": "llmnr", "description": "Link-Local Multicast Name Resolution"},
}

COMMON_PORTS = {
    "Top 100": [
        21, 22, 23, 25, 53, 80, 110, 111, 135, 139, 143, 443, 445, 993, 995,
        1723, 3306, 3389, 5900, 8080, 8443, 8888, 27017, 6379, 5432, 1433,
        1521, 2375, 9200, 9300, 11211, 6667, 5060, 69, 137, 138, 161, 162,
        500, 514, 520, 1900, 5353, 4500, 123, 67, 68, 5900, 5985, 5986,
        1080, 8161, 9042, 9092, 15672, 61616, 2181, 4369, 5672, 6443,
        10250, 6000, 7474, 9090, 3000, 4848, 8086, 8500, 9000, 9001,
        10000, 16010, 50070, 27018, 27019, 28017, 2049, 873, 902,
        548, 631, 554, 587, 636, 1194, 1883, 2222, 3128, 3690,
        4444, 5000, 5001, 5432, 5555, 5601, 7000, 7070, 8000, 8008,
        8009, 8080, 8081, 8088, 8089, 9418, 20000,
    ],
    "Top 1000": list(range(1, 1001)),
    "Well-known (1-1023)": list(range(1, 1024)),
    "Registered (1024-49151)": list(range(1024, 49152)),
    "Web Services": [80, 443, 8080, 8443, 8000, 8008, 8081, 8088, 8089, 3000, 3001, 5000, 7070, 9000],
    "Database": [1433, 1521, 3306, 5432, 6379, 9200, 27017, 9042, 11211, 5984, 28015, 50000],
    "Remote Access": [22, 23, 3389, 5900, 5901, 5902, 10000, 5985, 5986, 2222],
    "Mail": [25, 110, 143, 465, 587, 993, 995, 2525],
    "File Transfer": [20, 21, 69, 115, 989, 990, 2049, 873, 3690, 9418],
    "Network Infra": [53, 67, 68, 123, 161, 162, 179, 389, 445, 500, 636],
    "Cloud/Container": [2375, 2376, 2379, 2380, 5000, 6443, 8500, 9000, 10250],
}


class ServiceDatabase:
    def __init__(self):
        self._db = SERVICES

    def lookup(self, port: int, protocol: str = "tcp") -> dict:
        key = (protocol.lower(), port)
        return self._db.get(key, {"name": "", "description": "Unknown Service", "cpe": ""})

    def get_service_name(self, port: int, protocol: str = "tcp") -> str:
        return self.lookup(port, protocol).get("name", "")

    def search(self, name: str) -> list:
        results = []
        name_lower = name.lower()
        for (proto, port), info in self._db.items():
            if name_lower in info.get("name", "").lower() or name_lower in info.get("description", "").lower():
                results.append((proto, port, info))
        return results

    def get_preset_ports(self, preset_name: str) -> list:
        return COMMON_PORTS.get(preset_name, [])

    def get_presets(self) -> list:
        return list(COMMON_PORTS.keys())